import type { Metadata } from 'next';
import React from 'react';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
  title: 'Trident E-Governance',
  description: 'Generated by create next app',
};

interface RootlayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootlayoutProps) {
  return (
    <div className="flex flex-row min-h-full">
      <Toaster />
      {/* <SideBarMenu /> */}
      <main className="flex-1">{children}</main>
    </div>
  );
}
