import type { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'Student Dashboard',   
  description: 'Generated by create next app',
}

interface RootlayoutProps {
    children: React.ReactNode
}

export default async function RootLayout({children}: RootlayoutProps) {
  return (
      <div>{children}</div>
  )
}
