// import { Toaster } from '@/components/ui/toaster'
import type { Metadata } from 'next'
import React from 'react'
import NSRNavbar from './components/NSR/NSRNavbar'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  title: 'Office Dashboard',   
  description: 'Generated by create next app',
}

interface RootlayoutProps {
    children: React.ReactNode
}

export default async function RootLayout({children}: RootlayoutProps) {
  return (
      <div className='flex flex-col'>
        <Toaster />
        <NSRNavbar />
        {children}
      </div>
  )
}
