import type { Metadata } from 'next'
import { Inter, Chakra_Petch, Exo_2 } from 'next/font/google'
import './globals.css'

// const inter = Inter({ subsets: ["latin"] });
// const chakra = Chakra_Petch({ weight: '400', subsets: ['latin'] })
const exo2 = Exo_2({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={exo2.className}>{children}</body>
    </html>
  )
}
