import type { Metadata } from 'next';
import React from 'react';
import { Toaster } from '@/components/ui/toaster';
import { FeesDetailsFilterProvider } from '@/app/(app)/(accounts)/components/FeeDetailsFilterProvider';

export const metadata: Metadata = {
  title: 'Fee Collection - Trident E-Governance',
  description: 'Generated by create next dashboard',
};

interface RootlayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootlayoutProps) {
  return (
    <div className="flex flex-row min-h-full">
      <FeesDetailsFilterProvider>
        <Toaster />
        {/* <SideBarMenu /> */}
        <main className="flex-1">{children}</main>
      </FeesDetailsFilterProvider>
    </div>
  );
}
